# Generated by Django 5.2 on 2025-08-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioc',
            name='senha',
            field=models.CharField(default='sem_senh', max_length=100),
            preserve_default=False,
        ),
    ]
