# Generated by Django 5.2 on 2025-09-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_usuarioc_senha'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuarioC',
            new_name='Usuario',
        ),
    ]
