# Generated by Django 5.2 on 2025-10-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_calendariofrequencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendariofrequencia',
            name='presente',
        ),
    ]
