# Generated by Django 5.1.6 on 2025-11-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_calendariofrequencia'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendariofrequencia',
            unique_together={('usuario', 'data')},
        ),
    ]
