# Generated by Django 5.1.6 on 2025-11-03 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_alter_calendariofrequencia_unique_together'),
        ('cadastro', '0005_remove_calendariofrequencia_presente'),
    ]

    operations = [
    ]
