# Generated by Django 5.1.6 on 2025-11-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_merge_20251103_1049'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendariofrequencia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='calendariofrequencia',
            name='presente',
            field=models.BooleanField(default=True),
        ),
    ]
