# Generated by Django 5.1.6 on 2025-11-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_alter_calendariofrequencia_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendariofrequencia',
            name='presente',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Cargas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pernas', models.IntegerField()),
                ('bracos', models.IntegerField()),
                ('costas', models.IntegerField()),
                ('peito', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.usuario')),
            ],
        ),
    ]
