# Generated by Django 5.2.5 on 2025-11-18 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_calendariofrequencia_presente_cargas'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoAtividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('Treino', models.TextField()),
                ('qtdexercicios', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.usuario')),
            ],
        ),
    ]
