# Generated by Django 5.1.6 on 2025-11-21 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_historicoatividades'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisicaoExclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_requisicao', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes_exclusao', to='cadastro.usuario')),
            ],
            options={
                'verbose_name': 'Requisição de Exclusão',
                'verbose_name_plural': 'Requisições de Exclusão',
                'ordering': ['-data_requisicao'],
            },
        ),
    ]
