# Generated by Django 5.1.6 on 2025-11-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_requisicaoexclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoatividades',
            name='data',
            field=models.DateField(),
        ),
    ]
