# Generated by Django 5.1.7 on 2025-11-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_alter_historicoatividades_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoatividades',
            name='cargas',
            field=models.IntegerField(default=0),
        ),
    ]
