# Generated by Django 5.1.7 on 2025-11-27 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_historicoatividades_cargas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supino_reto', models.IntegerField()),
                ('supino_inclinado', models.IntegerField()),
                ('crucifixo', models.IntegerField()),
                ('remada_curvada', models.IntegerField()),
                ('puxada_na_barra', models.IntegerField()),
                ('agachamento_livre', models.IntegerField()),
                ('leg_press', models.IntegerField()),
                ('desenvolvimento', models.IntegerField()),
                ('rosca_direta', models.IntegerField()),
                ('triceps_testa', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.usuario')),
            ],
        ),
    ]
