# Generated by Django 5.1.7 on 2025-11-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_ficha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='agachamento_livre',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='crucifixo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='desenvolvimento',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='leg_press',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='puxada_na_barra',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='remada_curvada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='rosca_direta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='supino_inclinado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='supino_reto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='triceps_testa',
            field=models.IntegerField(default=0),
        ),
    ]
