# Generated by Django 5.1.7 on 2025-12-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_alter_ficha_agachamento_livre_alter_ficha_crucifixo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoatividades',
            name='Treino',
            field=models.CharField(choices=[('Pernas', 'Treino de pernas'), ('Braços', 'Treino de braços'), ('Costas', 'Treino de costas'), ('Peito', 'Treino de peito')], max_length=6),
        ),
    ]
