# Generated by Django 5.1.7 on 2025-12-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_alter_historicoatividades_treino'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fotoperfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
