# Generated by Django 5.2.8 on 2025-12-02 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_usuario_fotoperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fotoperfil',
        ),
    ]
