# Generated by Django 5.2.5 on 2025-12-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_remove_usuario_fotoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fotoperfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
