# Generated by Django 5.2.5 on 2025-12-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0018_usuario_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fotoperfil',
            field=models.ImageField(blank=True, default='fotos_perfil/default.jpg', null=True, upload_to='fotos_perfil/'),
        ),
    ]
