# Generated by Django 5.1.6 on 2025-12-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0019_alter_usuario_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fotoperfil',
            field=models.TextField(blank=True, default='fotos_perfil/default.jpg', null=True),
        ),
    ]
