# Generated by Django 5.1.6 on 2025-12-02 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0020_alter_usuario_fotoperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fotoperfil',
        ),
    ]
