# Generated by Django 5.1.6 on 2025-12-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0021_remove_usuario_fotoperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fotoperfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/', verbose_name='Foto de Perfil'),
        ),
    ]
