# Generated by Django 5.2 on 2025-05-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membro',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
