# Generated by Django 5.1.6 on 2025-11-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membros', '0002_membro_peso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membro',
        ),
    ]
